SET SQL_SAFE_UPDATES = 0;
delete  from parseddocument where LetterType='training';
SET SQL_SAFE_UPDATES = 0;
delete  from encodedwords;
SET SQL_SAFE_UPDATES = 0;
delete  from ListOfWordsAndSentencesInEachDoc;
SET SQL_SAFE_UPDATES = 0;
delete  from diaconehotencoding;
SET SQL_SAFE_UPDATES = 0;
delete  from diacritics_and_undiacritized_letter_one_hot_encoding;
SET SQL_SAFE_UPDATES = 0;
delete  from undiaconehotencoding;
SET SQL_SAFE_UPDATES = 0;
delete from distinctdiacritics;
SET SQL_SAFE_UPDATES = 0;
delete from alldiacriticsinalldocuments;
SET SQL_SAFE_UPDATES = 0;
delete from dictionary;
SET SQL_SAFE_UPDATES = 0;
delete from arabic_letters_without_diacritics;
SET SQL_SAFE_UPDATES = 0;
delete from arabic_letters_with_diacritics;
SET SQL_SAFE_UPDATES = 0;
delete from arabic_diacritics;
SET SQL_SAFE_UPDATES = 0;
delete from labels;

SET SQL_SAFE_UPDATES = 0;
delete from parseddocument where LetterType='training';

SET SQL_SAFE_UPDATES = 0;
delete from parseddocument where UnDiacritizedCharacter = 'bos' or UnDiacritizedCharacter = 'space' or UnDiacritizedCharacter = 'eos';
delete from encodedwords where UnDiacritizedCharacter = 'bos' or UnDiacritizedCharacter = 'space' or UnDiacritizedCharacter = 'eos';
delete from ListOfWordsAndSentencesInEachDoc where word = 'bos' or word = 'space' or word = 'eos';
delete from arabic_letters_without_diacritics where arabic_letter = 'bos' or arabic_letter = 'space' or arabic_letter = 'eos';
delete from distinctdiacritics where id > 14;
delete from diaconehotencoding where idDiacritizedCharacter > 479;
SET SQL_SAFE_UPDATES = 0;
delete from listofwordsandsentencesineachdoc where idword < 237579;